import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../data/services/sensor_service.dart';
import '../data/services/audio_service.dart';
import '../data/services/storage_service.dart';
import '../data/services/dataset_recorder.dart';
import '../domain/models/app_state.dart';
import '../domain/models/face_features.dart';
import '../domain/engine/face_analyzer.dart';
import 'controllers/slap_controller.dart';
import 'controllers/dataset_controller.dart';

// -- Services --
final sensorServiceProvider = Provider<SensorService>((ref) => SensorService());
final audioServiceProvider = Provider<AudioService>((ref) => AudioService());
final storageServiceProvider = Provider<StorageService>((ref) => StorageService());

final datasetRecorderProvider = Provider<DatasetRecorder>((ref) {
  final storage = ref.watch(storageServiceProvider);
  return DatasetRecorder(storage);
});

// -- App State --
class AppStateNotifier extends Notifier<AppState> {
  @override
  AppState build() => AppState();

  void updateState(AppState newState) {
    state = newState;
  }
}

final appStateProvider = NotifierProvider<AppStateNotifier, AppState>(AppStateNotifier.new);

// -- Controllers --
final slapControllerProvider = NotifierProvider<SlapController, SlapState>(SlapController.new);

final datasetControllerProvider = NotifierProvider<DatasetController, DatasetState>(DatasetController.new);

// Provides the absolute path to the locally picked facial portrait
class SelectedImageNotifier extends Notifier<String?> {
  @override
  String? build() => null;
  void setImage(String? path) => state = path;
}
final selectedImageProvider = NotifierProvider<SelectedImageNotifier, String?>(SelectedImageNotifier.new);

// Manages the MLKit detection outputs for the layout overlays
class FaceFeaturesNotifier extends Notifier<FaceFeatures?> {
  @override
  FaceFeatures? build() => null;
  
  Future<void> analyze(String? path) async {
    if (path == null) {
      state = null;
      return;
    }
    state = await FaceAnalyzer.analyzeFace(path);
  }
}
final faceFeaturesProvider = NotifierProvider<FaceFeaturesNotifier, FaceFeatures?>(FaceFeaturesNotifier.new);

// Holds the synthesized image generated by the Python backend
class SadImageNotifier extends Notifier<String?> {
  @override
  String? build() => null;
  void setImage(String? path) => state = path;
}
final sadImageProvider = NotifierProvider<SadImageNotifier, String?>(SadImageNotifier.new);

// Tracks whether the user bypassed the image upload for a raw hit target
class ClassicModeNotifier extends Notifier<bool> {
  @override
  bool build() => false;
  void toggle(bool enable) => state = enable;
}
final classicModeProvider = NotifierProvider<ClassicModeNotifier, bool>(ClassicModeNotifier.new);
